### PR TITLE
146 create a fall declaration of fall on dependance app

### PR DESCRIPTION
**Pull request by aamadou**
Salam Mehdi,
Please check and test with me if possible before merging.
it took me some time but a lot of the code is straight-foreword reusable for future forms: (inline form in the middle, multichoice validation,...)

### CODE REVIEW

**Comment by aamadou** [comment]
@mehditerraneen this is broken because in  your last commit you forgot to delete the automatic migration added in dependence, it has the same number as my migration,
if you added it on purpose please let me know so I correct this from my side!

**Comment by mehditerraneen** [comment]
I think it's best to use the multiple choice field instead of the inlines inside the field
image
I'm using it in `CarePlanDetailInLine`

**Comment by aamadou** [comment]
@mehditerraneen please check new code, all comments have been taken into consideration, no charges added.

**Comment by mehditerraneen** [comment]
👍 I will test and merge

**Pull request merged**
