### PR TITLE
141 attach multiple files pictures to event stored in contabo s3

### PR DESCRIPTION
**Pull request by aamadou**

### CODE REVIEW

**Comment by aamadou** [comment]
here is the video
https://www.loom.com/share/4025b7c9d516403ab791076323c61bef

**Comment by aamadou** [comment]
the next step is multi file-upload, but I didn't want to do it before you approve this stage, as it would be an enhancement issue.

**Comment by mehditerraneen** [comment]
perfect @aamadou  can you just add a small non mandatory text field to allow entering a description to the attached file plz?

**Review by mehditerraneen — COMMENTED** [review]
ok

**Pull request merged**
